trigger:
   branches:
      include:
         - main

pool:
   vmImage: 'ubuntu-latest'

variables:
   - group: azure-static-web-apps-proud-water-0b542d000-variable-group

steps:
   - task: NodeTool@0
     inputs:
        versionSpec: '20.17.0'
     displayName: 'Install Node.js'

   - script: |
        npm install
     displayName: 'Install dependencies'

   - script: |
        npm run build
     displayName: 'Build React app'

   - task: AzureStaticWebApp@0
     inputs:
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_WATER_0B542D000)
        app_location: '/'
        api_location: ''
        output_location: 'dist'